# Generated by Django 4.2.6 on 2023-10-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "boardno",
                    models.AutoField(
                        db_column="boardNo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "boardtitle",
                    models.CharField(db_column="boardTitle", max_length=300),
                ),
                (
                    "boardcontent",
                    models.CharField(db_column="boardContent", max_length=2000),
                ),
                ("mid", models.CharField(db_column="mId", max_length=50)),
                ("boarddate", models.DateTimeField(db_column="boardDate")),
                (
                    "boardcount",
                    models.DecimalField(
                        db_column="boardCount", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "last_dt",
                    models.DateTimeField(blank=True, db_column="LAST_DT", null=True),
                ),
            ],
            options={
                "db_table": "Board",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Smember",
            fields=[
                (
                    "mid",
                    models.CharField(
                        db_column="mID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mname",
                    models.CharField(
                        blank=True, db_column="mName", max_length=100, null=True
                    ),
                ),
                (
                    "mmode",
                    models.CharField(
                        blank=True, db_column="mMode", max_length=1, null=True
                    ),
                ),
                (
                    "mpw",
                    models.CharField(
                        blank=True, db_column="mPW", max_length=50, null=True
                    ),
                ),
                (
                    "malias",
                    models.CharField(
                        blank=True, db_column="mAlias", max_length=100, null=True
                    ),
                ),
                (
                    "mbirth",
                    models.CharField(
                        blank=True, db_column="mBirth", max_length=20, null=True
                    ),
                ),
                (
                    "mzip_cd",
                    models.CharField(
                        blank=True, db_column="mZIP_CD", max_length=6, null=True
                    ),
                ),
                (
                    "maddr",
                    models.CharField(
                        blank=True, db_column="mADDR", max_length=100, null=True
                    ),
                ),
                (
                    "mdetl_addr",
                    models.CharField(
                        blank=True, db_column="mDETL_ADDR", max_length=100, null=True
                    ),
                ),
                (
                    "mphone",
                    models.CharField(
                        blank=True, db_column="mPHONE", max_length=15, null=True
                    ),
                ),
                (
                    "memail",
                    models.CharField(
                        blank=True, db_column="mEMAIL", max_length=50, null=True
                    ),
                ),
                (
                    "mmemo",
                    models.CharField(
                        blank=True, db_column="mMEMO", max_length=1000, null=True
                    ),
                ),
                (
                    "inst_dt",
                    models.DateTimeField(blank=True, db_column="INST_DT", null=True),
                ),
                (
                    "last_dt",
                    models.DateTimeField(blank=True, db_column="LAST_DT", null=True),
                ),
            ],
            options={
                "db_table": "sMember",
                "managed": False,
            },
        ),
    ]
